# Generated by Django 5.2 on 2025-05-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'to do'), (1, 'in progress'), (2, 'done')], default=1)),
            ],
        ),
    ]
