# Generated by Django 5.2 on 2025-05-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancard',
            name='status',
            field=models.IntegerField(choices=[(0, 'to-do'), (1, 'in-progress'), (2, 'done')], default=0),
        ),
    ]
