# Generated by Django 5.2 on 2025-05-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='kanban_card',
            new_name='card',
        ),
    ]
